# Generated by Django 2.2.5 on 2019-11-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stoke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stoke',
        ),
    ]
