# Generated by Django 2.2.5 on 2019-11-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_stoke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stoke',
        ),
    ]
