# Generated by Django 2.2.5 on 2019-11-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_stoke'),
    ]

    operations = [
        migrations.CreateModel(
            name='stokein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField(max_length=10)),
                ('img', models.FileField(null=True, upload_to='')),
                ('itemname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('type', models.BooleanField(default=False)),
            ],
        ),
    ]
