# Generated by Django 2.2.5 on 2019-12-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_amount_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='amount',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
