# Generated by Django 2.2.7 on 2021-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_amount_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='amount',
        ),
        migrations.DeleteModel(
            name='busket',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='stokein',
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
